
version: 2.1

orbs:
  python: circleci/python@1.5.0


jobs:
  build: 
   
    docker:
      - image: cimg/python:3.10.2
   
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: install packages
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      - run:
          name: Run lint
          command: |
            . venv/bin/activate
            make lint


workflows:
  my-workflow: 
    jobs:
      - build
